# como es temporal para compilar usamos la version full en vez de la -alpine
FROM node:lts AS builder

WORKDIR /usr/src/

COPY package.json ./

# COPY .npmrc package.json ./
RUN npm i
ENV PATH="./node_modules/.bin:$PATH"
COPY . ./

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.18-alpine

WORKDIR /opt/ng
# Use root user to copy dist folder and modify user access to specific folder
USER root

# Copy application and custom NGINX configuration

#  Copy application> modified default output Path to dist in angular.json projects.test-app.architect.build.outputPath
COPY --from=builder /usr/src/dist/ /usr/share/nginx/html

# Custom NGINX configuration, for fallback url (app is angualr spa uses clitn-side routing)
COPY nginx-custom.conf /etc/nginx/conf.d/default.conf

# Setup unprivileged user 1001
RUN chown -R 1001 /usr/share/nginx/html

# Use user 1001
USER 1001

# Expose a port that is higher than 1024 due to unprivileged access
EXPOSE 8080

CMD ["/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/assets/settings.template.json > /usr/share/nginx/html/assets/settings.json && exec nginx -g 'daemon off;'"]
